all:
	$(MAKE) -C "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2/build"
kissat:
	$(MAKE) -C "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2/build" kissat
tissat:
	$(MAKE) -C "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2/build" tissat
clean:
	rm -f "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2"/makefile
	-$(MAKE) -C "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2/build" clean
	rm -rf "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2/build"
coverage:
	$(MAKE) -C "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2/build" coverage
indent:
	$(MAKE) -C "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2/build" indent
test:
	$(MAKE) -C "/home/mint1/Desktop/kissat-MAB-1.0.3-79d8d8f2/build" test
.PHONY: all clean coverage indent kissat test tissat
