all:
	$(MAKE) -C "/home/mint1/Desktop/kissat_gb/build"
clean:
	rm -f "/home/mint1/Desktop/kissat_gb"/makefile
	-$(MAKE) -C "/home/mint1/Desktop/kissat_gb/build" clean
	rm -rf "/home/mint1/Desktop/kissat_gb/build"
coverage:
	$(MAKE) -C "/home/mint1/Desktop/kissat_gb/build" coverage
indent:
	$(MAKE) -C "/home/mint1/Desktop/kissat_gb/build" indent
test:
	$(MAKE) -C "/home/mint1/Desktop/kissat_gb/build" test
.PHONY: all clean coverage indent test
